#[derive(Debug, seaography_derive :: QueryRoot)]
#[seaography(entity = "crate::entities::artists")]
#[seaography(entity = "crate::entities::tracks")]
#[seaography(entity = "crate::entities::customers")]
#[seaography(entity = "crate::entities::invoices")]
#[seaography(entity = "crate::entities::genres")]
#[seaography(entity = "crate::entities::playlist_track")]
#[seaography(entity = "crate::entities::invoice_items")]
#[seaography(entity = "crate::entities::employees")]
#[seaography(entity = "crate::entities::playlists")]
#[seaography(entity = "crate::entities::media_types")]
#[seaography(entity = "crate::entities::albums")]
pub struct QueryRoot;
