[package]
name = "seaography_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.2.2"
seaography_types = { path = "../seaography_types" }
seaography_discoverer = { path = "../seaography_discoverer" }
seaography_generator = { path = "../seaography_generator" }
clap = { version = "3.2.6", features = ["derive"] }
async-std = { version = "1.12.0", features = [ "attributes", "tokio1" ] }
sea-orm-codegen={ git="https://github.com/SeaQL/sea-orm", branch="684-seaorm-entity-generator-does-not-support-blob-fields"}