//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

pub mod prelude;

pub mod albums;
pub mod artists;
pub mod customers;
pub mod employees;
pub mod genres;
pub mod invoice_items;
pub mod invoices;
pub mod media_types;
pub mod playlist_track;
pub mod playlists;
pub mod tracks;
