//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

pub mod prelude ;

pub mod invoices ;
pub mod genres ;
pub mod playlists ;
pub mod invoice_items ;
pub mod playlist_track ;
pub mod customers ;
pub mod employees ;
pub mod artists ;
pub mod media_types ;
pub mod albums ;
pub mod tracks ;