//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "actor")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub actor_id: i64,
    pub first_name: String,
    pub last_name: String,
    pub last_update: DateTimeUtc,
    #[sea_orm(has_many, via = "film_actor")]
    pub films: HasMany<super::film::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
