//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "address")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub address_id: i64,
    pub address: String,
    pub address2: Option<String>,
    pub district: String,
    pub city_id: i64,
    pub postal_code: Option<String>,
    pub phone: String,
    pub last_update: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "city_id",
        to = "city_id",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    pub city: HasOne<super::city::Entity>,
    #[sea_orm(has_many)]
    pub customers: HasMany<super::customer::Entity>,
    #[sea_orm(has_many)]
    pub staff: HasMany<super::staff::Entity>,
    #[sea_orm(has_many)]
    pub stores: HasMany<super::store::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
