//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.14

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "category")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub category_id: i16,
    pub name: String,
    pub last_update: DateTimeUtc,
    #[sea_orm(has_many, via = "film_category")]
    pub films: HasMany<super::film::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
