//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "city")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub city_id: i64,
    pub city: String,
    pub country_id: i16,
    pub last_update: DateTimeUtc,
    #[sea_orm(has_many)]
    pub addresses: HasMany<super::address::Entity>,
    #[sea_orm(
        belongs_to,
        from = "country_id",
        to = "country_id",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    pub country: HasOne<super::country::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
