//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "country")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub country_id: i16,
    pub country: String,
    pub last_update: Option<DateTimeUtc>,
    #[sea_orm(has_many)]
    pub cities: HasMany<super::city::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
