//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "film_category")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub film_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub category_id: i16,
    pub last_update: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "category_id",
        to = "category_id",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    pub category: HasOne<super::category::Entity>,
    #[sea_orm(
        belongs_to,
        from = "film_id",
        to = "film_id",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    pub film: HasOne<super::film::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
