#![doc = " SeaORM Entity. Generated by sea-orm-codegen 0.9.1"]
use sea_orm::entity::prelude::*;
#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;
impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "genres"
    }
}
#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveModel,
    DeriveActiveModel,
    async_graphql :: SimpleObject,
    seaography_derive :: Filter,
)]
#[sea_orm(table_name = "genres")]
#[graphql(complex)]
#[graphql(name = "Genres")]
pub struct Model {
    pub genre_id: i32,
    pub name: Option<String>,
}
#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    #[sea_orm(column_name = "GenreId")]
    GenreId,
    #[sea_orm(column_name = "Name")]
    Name,
}
#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    GenreId,
}
impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}
#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Tracks,
}
impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::GenreId => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(None).def().null(),
        }
    }
}
#[seaography_derive::relation]
impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Tracks => Entity::has_many(super::tracks::Entity).into(),
        }
    }
}
impl Related<super::tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tracks.def()
    }
}
impl ActiveModelBehavior for ActiveModel {}
