//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "inventory")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub inventory_id: i64,
    pub film_id: i64,
    pub store_id: i64,
    pub last_update: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "film_id",
        to = "film_id",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    pub film: HasOne<super::film::Entity>,
    #[sea_orm(has_many)]
    pub rentals: HasMany<super::rental::Entity>,
    #[sea_orm(
        belongs_to,
        from = "store_id",
        to = "store_id",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    pub store: HasOne<super::store::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
