//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "payment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub payment_id: i64,
    pub customer_id: i64,
    pub staff_id: i16,
    pub rental_id: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))")]
    pub amount: Decimal,
    pub payment_date: DateTimeUtc,
    pub last_update: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "customer_id",
        to = "customer_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub customer: HasOne<super::customer::Entity>,
    #[sea_orm(
        belongs_to,
        from = "rental_id",
        to = "rental_id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub rental: HasOne<super::rental::Entity>,
    #[sea_orm(
        belongs_to,
        from = "staff_id",
        to = "staff_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub staff: HasOne<super::staff::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
