//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.14

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rental")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub rental_id: i32,
    #[sea_orm(unique_key = "unique")]
    pub rental_date: DateTimeUtc,
    #[sea_orm(unique_key = "unique")]
    pub inventory_id: i32,
    #[sea_orm(unique_key = "unique")]
    pub customer_id: i32,
    pub return_date: Option<DateTimeUtc>,
    pub staff_id: i16,
    pub last_update: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "customer_id",
        to = "customer_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub customer: HasOne<super::customer::Entity>,
    #[sea_orm(
        belongs_to,
        from = "inventory_id",
        to = "inventory_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub inventory: HasOne<super::inventory::Entity>,
    #[sea_orm(has_many)]
    pub payments: HasMany<super::payment::Entity>,
    #[sea_orm(
        belongs_to,
        from = "staff_id",
        to = "staff_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub staff: HasOne<super::staff::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
