//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "store")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub store_id: i64,
    pub manager_staff_id: i16,
    pub address_id: i64,
    pub last_update: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "address_id",
        to = "address_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub address: HasOne<super::address::Entity>,
    #[sea_orm(has_many)]
    pub customers: HasMany<super::customer::Entity>,
    #[sea_orm(has_many)]
    pub inventories: HasMany<super::inventory::Entity>,
    #[sea_orm(
        belongs_to,
        from = "manager_staff_id",
        to = "staff_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub staff: HasOne<super::staff::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
