name: Testing

on: push

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions-rs/toolchain@v1
                with:
                    profile: minimal
                    toolchain: stable
                    override: true
            -   uses: actions-rs/cargo@v1
                with:
                    command: check
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions-rs/toolchain@v1
                with:
                    profile: minimal
                    toolchain: stable
                    override: true
            -   uses: actions-rs/cargo@v1
                with:
                    command: test
                    args: --workspace
    fmt:
        name: Format
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions-rs/toolchain@v1
                with:
                    profile: minimal
                    toolchain: stable
                    override: true
            -   run: rustup component add rustfmt
            -   uses: actions-rs/cargo@v1
                with:
                    command: fmt
                    args: --all -- --check

    clippy:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions-rs/toolchain@v1
                with:
                    profile: minimal
                    toolchain: stable
                    override: true
            -   run: rustup component add clippy
            -   uses: actions-rs/cargo@v1
                with:
                    command: clippy
                    args: -- -D warnings

    integration-sqlite:
        name: SQLite integration tests
        runs-on: ubuntu-latest
        needs:
            - check
            - test
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions-rs/toolchain@v1
                with:
                    profile: minimal
                    toolchain: stable
                    override: true
            -   name: Remove generated folder
                run: rm -rf ./generated/src
            -   name: Move database
                run: cp ./chinook.db ./generated/chinook.db
            -   uses: actions-rs/cargo@v1
                with:
                    command: run
                    args: sqlite://chinook.db generated ./generated
            -   name: Integration tests
                working-directory: ./generated
                run: cargo test